app/models/billing.rb
test/models/billing_test.rb

Model validations

---

db/migrate/20171019021225_add_order_to_billings.rb
db/schema.rb

changed schema
ymls and tests still need to be changed

billing belongs to an order instead of a user

---

app/controllers/products_controller.rb
config/routes.rb
test/controllers/products_controller_test.rb
test/test_helper.rb

Includes tests for OAuth which is not implemented yet

Created Product controller tests

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/billings_controller.rb
app/controllers/products_controller.rb
app/views/products/home.html.erb
config/routes.rb
test/controllers/billings_controller_test.rb
test/controllers/products_controller_test.rb
test/test_helper.rb

Added under Products controller (products#home)
Put in a template view (just says home page), and also a basic test (get root_path must return :success) in Products controller test
If there are merge issues, the changes are small, so it should be easy to just copy and paste into code base.

Add home page (root path)

---

Gemfile
Gemfile.lock
app/controllers/billings_controller.rb
app/views/billings/new.html.erb
app/views/layouts/_flash.html.erb
app/views/layouts/application.html.erb
test/controllers/billings_controller_test.rb
test/test_helper.rb

Add routes/methods to add billing info to an order
Also added a form for inputting billing info
Also added partial to view flash messages to the app layout view (so this will appear on any of the site pages)
**Issues**
- How do we add text field not connected to a model? Easier to just edit the db schema? (for CVV code)
- When we have an order confirmation page, we'll need to update the controller and tests to reflect the redirect
- Temp commented out the OmniAuth stuff in test helper since it was making the tests fail

Billing controller

---

app/helpers/application_helper.rb

created display_address and display_cc methods

---

app/controllers/products_controller.rb
app/models/product.rb
config/routes.rb

Note: May need to be refactored for categories nested under products instead of products under categories.

Show products of a category page

---

app/controllers/application_controller.rb
app/controllers/billings_controller.rb
app/controllers/reviews_controller.rb
app/models/billing.rb
app/models/merchant.rb
app/models/order.rb
app/models/review.rb
app/views/billings/new.html.erb
app/views/layouts/application.html.erb
app/views/orders/confirmation.html.erb
config/routes.rb
test/controllers/billings_controller_test.rb
test/controllers/reviews_controller_test.rb
test/models/order_test.rb
test/models/review_test.rb

No delete or index for review. We can implement delete later if time, and I figured the only time reviews would be indexed is when they're filtered through the product (i.e. show all the reviews for a product). And it made more sense to have that as an instance variable as part of the product display page.
Will have to be retested when OAuth implemented.

Review controller

---

.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/sessions.js
app/assets/stylesheets/sessions.scss
app/controllers/application_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/helpers/sessions_helper.rb
app/models/merchant.rb
app/views/layouts/application.html.erb
app/views/merchants/new.html.erb
app/views/orders/confirmation.html.erb
app/views/sessions/create.html.erb
app/views/sessions/login.html.erb
config/initializers/omniauth.rb
config/routes.rb
test/controllers/sessions_controller_test.rb
test/fixtures/merchants.yml
test/models/merchant_test.rb
test/test_helper.rb

You need to create a .env file in the root project folder
Secrets in Slack

Oauth setup

---

app/controllers/billings_controller.rb
app/controllers/products_controller.rb
app/views/orders/cart.html.erb

- Added cart checkout button logic and connected it to new Billing Route
- when completing a transaction, reset the session's order_id
- started remove cart logic but haven't implemented it yet (got lazy switching branches, sorry)

Fix cart checkout

---

app/controllers/products_controller.rb
app/models/order.rb
app/views/orders/cart.html.erb
config/routes.rb

- changed route for remove_to_cart to a PATCH
- added add_to_cart route back
- transferred logic from add/remove from Product Controller to Order Model
- Added Delete button for each item in cart (removes the item from cart)

Remove product from cart

---

app/controllers/application_controller.rb
test/controllers/application_contoller_test.rb
test/controllers/billings_controller_test.rb
test/test_helper.rb

Hopefully this doesn't mess anything up

reflected on application controller and fixed simplecov in test_helper

---

app/controllers/sessions_controller.rb
app/models/order.rb
test/fixtures/orders.yml

Rec session data

---

app/controllers/application_controller.rb
app/controllers/products_controller.rb
app/controllers/sessions_controller.rb
config/routes.rb
test/controllers/products_controller_test.rb
test/controllers/reviews_controller_test.rb

Added authentication / merchant can't edit products they don't own to products controller and added tests.
STILL NEEDS: tests for add to and remove from cart

Products controller

---

app/controllers/categories_controller.rb
app/models/category.rb
app/models/product.rb
config/routes.rb
test/controllers/categories_controller_test.rb
test/fixtures/categories.yml
test/models/category_test.rb
test/models/product_test.rb

built out tests and methods to help categories

Categories

---

app/assets/stylesheets/application.css
app/views/layouts/application.html.erb

There is a working overlay button now!

Overlay button added, needs tweaking, but connects to all products page.

---

app/controllers/merchants_controller.rb
app/models/merchant.rb
app/views/merchants/_items.html.erb
app/views/merchants/show.html.erb
test/models/merchant_test.rb

added extra row to merchant tables for various revenue totals

Revenue methods

---

app/assets/stylesheets/application.css
app/controllers/application_controller.rb
app/controllers/billings_controller.rb
app/controllers/merchants_controller.rb
app/controllers/orders_controller.rb
app/controllers/products_controller.rb
app/controllers/reviews_controller.rb
app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/merchants/_items.html.erb
app/views/merchants/show.html.erb
test/controllers/billings_controller_test.rb
test/controllers/orders_controller_test.rb
test/controllers/products_controller_test.rb
test/controllers/reviews_controller_test.rb
test/controllers/sessions_controller_test.rb
test/models/product_test.rb

redirect root_path links to products_path links
Set up merchant controller views--still need to add links to change visibility, etc
ALSO: 
changed app layout (fixed yield, added header tags)
added flash styling to CSS
temporarily commented out home page slideshow (in CSS comments)

Merchant controller etc

---

app/controllers/products_controller.rb
app/views/products/_form.html.erb
app/views/products/edit.html.erb
app/views/products/new.html.erb
db/seed_csv/categories.csv

- created _form partial for new and edit
- changed controller so that it filters by visibility and by alphabetical order

Create product form partial

---

app/controllers/application_controller.rb
app/controllers/merchants_controller.rb
app/controllers/order_items_controller.rb
app/controllers/products_controller.rb
app/models/order.rb
app/models/order_item.rb
app/models/product.rb
app/views/layouts/application.html.erb
app/views/merchants/_items.html.erb
app/views/merchants/show.html.erb
app/views/orders/confirmation.html.erb
test/controllers/application_contoller_test.rb
test/controllers/merchants_controller_test.rb
test/controllers/order_items_controller_test.rb
test/controllers/products_controller_test.rb
test/controllers/sessions_controller_test.rb
test/models/order_item_test.rb
test/models/order_test.rb
test/models/product_test.rb

lots of random tests and stuff.
Also added update inventory capability to merchant acct page when change status

Merchant controller

---

app/assets/stylesheets/products.scss
app/controllers/products_controller.rb
app/controllers/reviews_controller.rb
app/helpers/application_helper.rb
app/models/order.rb
app/views/products/index.html.erb
app/views/products/show.html.erb
app/views/reviews/_review_form.html.erb
app/views/reviews/new.html.erb

- Created form for new reviews, edited css for products index, and displays all reviews of a product in their show page
- Corrected permission for products show page so that merchant can see an invisible product and a guest user can see the other visible products

Permission for product show and reviews

---

app/controllers/application_controller.rb
app/controllers/merchants_controller.rb
app/controllers/orders_controller.rb
app/views/layouts/application.html.erb
app/views/merchants/_items.html.erb
app/views/orders/confirmation.html.erb
app/views/orders/show.html.erb
config/routes.rb

added routes and views to display an order from the merchant dashboard

Order confirmation

---

app/controllers/products_controller.rb
app/controllers/sessions_controller.rb
app/views/categories/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
test/controllers/products_controller_test.rb
test/fixtures/products.yml

- Fixed product controller tests related to photo_url problem in fixtures
- added quantity in params for all tests on add_to_cart
- changed category related urls so that instead of going to category.id, use category.name

Edit product show bug test

---

app/views/merchants/_items.html.erb
app/views/merchants/show.html.erb

in case anyone forgot to do this part

added list of purchase to logged in users account
